import base64
import io
import unittest

from PIL import Image, ImageDraw

from edgeglyph.cli import _normalize_legacy_argv, build_parser
from edgeglyph.schema import coerce_options, defaults_for, mode_schema
from edgeglyph.web.server import application_schema, render_payload


def encoded_test_image():
    image = Image.new("RGB", (64, 64), "white")
    draw = ImageDraw.Draw(image)
    draw.ellipse((8, 6, 56, 58), fill="#e3cf62", outline="#3b2730", width=4)
    output = io.BytesIO()
    image.save(output, format="PNG")
    return "data:image/png;base64," + base64.b64encode(output.getvalue()).decode()


class SchemaTests(unittest.TestCase):
    def test_modes_have_independent_defaults(self):
        schema = mode_schema()
        self.assertEqual(set(schema), {"block", "glyph"})
        self.assertEqual(defaults_for("block")["colors"], 4)
        self.assertEqual(defaults_for("glyph")["colors"], 16)

    def test_options_are_coerced_and_bounded(self):
        options = coerce_options("block", {"cols": "72", "zoom": "0.9"})
        self.assertEqual(options["cols"], 72)
        self.assertEqual(options["zoom"], 0.9)
        with self.assertRaisesRegex(ValueError, "Columns must be at most"):
            coerce_options("block", {"cols": 500})
        with self.assertRaisesRegex(ValueError, "unknown block options"):
            coerce_options("block", {"font": "irrelevant.ttf"})


class CliTests(unittest.TestCase):
    def test_explicit_mode_parser(self):
        args = build_parser().parse_args(["block", "portrait.png", "--colors", "3"])
        self.assertEqual(args.command, "block")
        self.assertEqual(args.colors, 3)
        self.assertFalse(hasattr(args, "font"))

    def test_legacy_style_is_translated(self):
        self.assertEqual(
            _normalize_legacy_argv(
                ["portrait.png", "--style", "glyph", "--font", "mono.ttf"]
            ),
            ["glyph", "portrait.png", "--font", "mono.ttf"],
        )


class WebTests(unittest.TestCase):
    def test_application_schema_exposes_fonts_separately(self):
        schema = application_schema()
        self.assertIn("modes", schema)
        self.assertIn("fonts", schema)
        self.assertIn("font", schema["defaults"])

    def test_block_request_returns_all_download_formats(self):
        result = render_payload(
            {
                "mode": "block",
                "source": encoded_test_image(),
                "options": {"cols": 12, "rows": 6, "colors": 3, "oversample": 3},
            }
        )
        self.assertTrue(result["preview"].startswith("data:image/png;base64,"))
        self.assertIn("Generated by EdgeGlyph", result["lua"])
        self.assertEqual(result["metrics"]["mode"], "block")
        self.assertEqual(result["metrics"]["cols"], 12)
        self.assertLessEqual(len(result["palette"]), 3)


if __name__ == "__main__":
    unittest.main()
